<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="AutoGeneratedLinks.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:HyperLink 
            ID="SumLink" 
            runat="server"
            Text="10+20"
            NavigateUrl =" <%$RouteUrl:operation=sum, x=10, y=20, routename=Calculator %>"
            ></asp:HyperLink>
            <br />
            <asp:HyperLink 
            ID="SubLink" 
            runat="server"
            Text="10-20"
            NavigateUrl =" <%$RouteUrl:operation=sub, x=10, y=20, routename=Calculator %>"
            ></asp:HyperLink>
        </div>
    </form>
</body>
</html>
